### PR TITLE
Include AMD build in npm tarball so Ember can use luxon directly

### PR DESCRIPTION
**Pull request by tim-evans**
Hello! Thanks for this wonderful library.

This is more of a suggested PR, since [ember-luxon](https://github.com/willrax/ember-luxon) exists.

Essentially, I would like to import luxon directly into my Ember application, so I can keep up to date with the most recent versions of luxon without depending on another package to be published. The change here adds an AMD output, which would allow Ember apps / addons to directly import luxon into their application without running rollup. I understand that adding this build file will result in some bloat in the npm tarball, so I've added that info below:

| Before | After |
|--------|------|
| 410704 bytes | 532358 bytes |

This adds ~100K to the npm tarball.

Once again, thanks for this library ❤️

### CODE REVIEW

**Comment by icambron** [comment]
Sure

**Comment by icambron** [comment]
Will release this soon in 0.5.7

**Comment by tim-evans** [comment]
Thanks @icambron

**Comment by icambron** [comment]
This was released in 0.5.7

**Pull request merged**
