### PR TITLE
Fix ES6 minify

### LINKED ISSUE #771: URL broken in install instructions
It links to here which is 404: `https://moment.github.io/luxon/es6/luxon.min.js`

https://moment.github.io/luxon/docs/manual/install.html#es6

### PR DESCRIPTION
**Pull request by pgcalixto**
This is an attempt to resolve #771.

### CODE REVIEW

**Comment by pgcalixto** [comment]
@icambron, how is the broken URL re-generated (https://moment.github.io/luxon/es6/luxon.min.js)?

**Comment by pgcalixto** [comment]
Also, I couldn't help but notice that the package-lock still had the previous version (you can see in the diff: `"version": "1.24.1"`).

It would be ideal for it to match the version in package.json. Is there an automated process to bump them both and keep them matching?

**Comment by icambron** [comment]
@pgcalixto I'm not sure. I'll figure that out when I do the next release, which should be very soon

**Comment by icambron** [comment]
Thanks!

**Pull request merged**
