### PR TITLE
updated doc for react native android

### PR DESCRIPTION
**Pull request by roadmanfong**
https://github.com/moment/luxon/issues/604

### CODE REVIEW

**Comment by icambron** [comment]
Looks good. Can you sign the CLA?

**Comment by icambron** [comment]
@roadmanfong I'd love to merge this, but I need the CLI signed first

**Comment by sallar** [comment]
@icambron is there a way to get this into the official docs? It's beneficial for newcomers to know about this feature. I found it accidentally. I can send a fresh PR and sign the CLA if the original author doesn't do it.

**Comment by icambron** [comment]
Yeah, I guess create a new PR

**Pull request closed without merging**
