### PR TITLE
Fix linting errors in test/helpers.js

### PR DESCRIPTION
**Pull request by GillesDebunne**
Just a run of `npm run lint!`.

Should be merge first, so that other PRs can ignore these file changes

### CODE REVIEW

**Comment by stefanpearson** [comment]
Thanks, I'll remove this from https://github.com/moment/luxon/pull/470

**Comment by GillesDebunne** [comment]
That should be done for you. As soon as this PR gets merged, these changes
should no longer appear in your own PR.

At least, that's what I expect for #464
<https://github.com/moment/luxon/pull/464>. Worst case, you need to rebase
first.

Gilles

**Comment by stefanpearson** [comment]
Ok :+1:, looks like linting happens on a pre-commit hook anyway, so any commits will incorporate these changes.

**Comment by icambron** [comment]
Thanks for cleaning this up

**Pull request merged**
