### PR TITLE
docs(datetime): fix typo

### PR DESCRIPTION
**Pull request by blackwindforce**

### CODE REVIEW

**Comment by icambron** [comment]
Thanks, this looks good. Can you sign the CLA?

**Comment by blackwindforce** [comment]
> Thanks, this looks good. Can you sign the CLA?

The certificate on https://cla.js.foundation/moment/luxon?pullRequest=987 was revoked. Is there another way to proceed it?

**Comment by icambron** [comment]
@blackwindforce meaning the SSL cert? Not seeing that from here. Can you double check? If it's still an issue, I'll I'll ask the JS foundation

**Comment by blackwindforce** [comment]
@icambron Yes, I've double checked. That's why I didn't sign CLA in the first place. Would you please contact JS foundation? Here's the report https://www.ssllabs.com/ssltest/analyze.html?d=cla.js.foundation, and my browser also blocks the site with NET::ERR_CERT_REVOKED.

**Comment by blackwindforce** [comment]
@icambron I've signed CLA, please review.

**Comment by icambron** [comment]
Thanks!

**Pull request merged**
