### PR TITLE
Add X and x tokens to toFormat that return the Date in epoch seconds and milliseconds respectively

### PR DESCRIPTION
**Pull request by ivosabev**
Let me know if this is of interest and I will add the needed docs to the pull request.

### CODE REVIEW

**Comment by icambron** [comment]
First, sorry for the ridiculously long delay on getting to this.

A few thoughts:

I don't like `toUnix()` since it doesn't seem to add much above `toMillis()/1000`. The new token is a different story; I can see how it's painful to handle that in userland. I'm thus going to close your other PR with both `toUnix` and the new token in favor of this one.

To get this over the line, we just need docs and tests.

**Comment by ivosabev** [comment]
Added the two tokens `x` and `X` + tests ands docs. Let me know if there is anything else needed.

**Comment by icambron** [comment]
Looks great. Thanks for the contribution.

I'll release this soon.

**Comment by dasa** [comment]
Could these be supported in `fromFormat` as well?

**Pull request merged**
