### PR TITLE
Fix typo in docs/why.md

### PR DESCRIPTION
**Pull request by mickdekkers**

### CODE REVIEW

**Comment by icambron** [comment]
oops

image

Also, I know it seems ridiculous to sign a CLA for a one-word fix, but them's the rules.

**Comment by icambron** [comment]
@mickdekkers if you click the little CLA button it takes you to a page where you click more stuff. Then I can merge this.

**Comment by mickdekkers** [comment]
@icambron Done  ✔️ 

Happy merging 😄

**Comment by icambron** [comment]
Thanks

**Pull request merged**
