### PR TITLE
Implemented fromMillis() to verify args

### LINKED ISSUE #300: Check the milliseconds argument of fromMillis
I was not paying attention when I passed a `DateTime` object to the `fromMillis` method.
The resulting date seemed to be valid, except it doesn't: its internal value gets populated with the `DateTime` instance, breaking any subsequent comparison or calculation.

I would expect `fromMillis` to return an invalid date.

Some tests from the curent version (`v1.3.1`):

```javascript
const DateTime = require('luxon').DateTime;
const now = DateTime.local();
const lastYear = now.minus({ years: 1 });
const wrongDate = DateTime.fromMillis('now');
const testDate = DateTime.fromMillis(now);

/* Expected*/
console.log(now.isValid && now.toISO()); // 2018-07-17T14:54:22.448+02:00
console.log(lastYear.isValid && lastYear.toISO()); // 2017-07-17T14:54:22.448+02:00
console.log(now.diff(lastYear).as('days')); // 365
console.log(now > lastYear); // true

/* Not expected */
console.log(testDate.isValid && testDate.toISO()); // 2018-07-17T14:54:22.448+02:00
console.log(wrongDate.isValid && wrongDate.toISO()); // 0NaN-NaN-NaNTNaN:NaN:NaN.NaN-NaN:NaN
console.log(now.equals(testDate)); // false
console.log(testDate > lastYear); // false
console.log(testDate.diff(lastYear).as('days')); // 0
console.log(testDate.valueOf() instanceof DateTime && testDate.valueOf().toISO()); // 2018-07-17T14:54:22.448+02:00
```

### PR DESCRIPTION
**Pull request by taeukme**
Fixes #300

### CODE REVIEW

**Comment by icambron** [comment]
Looks good, but needs a test

**Comment by taeukme** [comment]
The tests are up but coverage seems to be failing.

**Comment by icambron** [comment]
Yeah, the coverage is failing because the tests never follow the fail code path. We already have tests for `fromMillis`, but you need one for the fail case, like `expect(DateTime.fromMillis('goat').toThrow(...`

**Comment by icambron** [comment]
Awesome. Thanks for the contribution!

**Pull request merged**
