### PR TITLE
fixed issue #1233

### PR DESCRIPTION
**Pull request by CristiMacovei**
Made a couple of changes to the code to solve issue #1233

### CODE REVIEW

**Comment by icambron** [comment]
Thanks. This will need tests though

**Comment by CristiMacovei** [comment]
It did pass the unit tests for duration/. I can write more tests there if that's helpful 
Let me know if there's any other way I can help

**Comment by icambron** [comment]
@CristiMacovei Yeah, so in general if you fix an issue, you write a test that would fail without your change and then make it pass with your code. That way, if someone make a change that breaks your fix, then they'll right away.

**Comment by CristiMacovei** [comment]
Yeah, I'll get to that and I'll open another PR. Sorry, didn't know I was supposed to do that first

**Comment by icambron** [comment]
It's ok for the test to be in the same PR, even if it only fails without your other code changes.

**Pull request closed without merging**
