### PR TITLE
Update support matrix

### PR DESCRIPTION
**Pull request by sandstrom**
Node 6 is EOL (https://nodejs.org/en/about/releases/) so I removed it. Also removed other browsers that are very old.

Updated matrix to reflect that Safari now support relative time formatting since 14.4.

### CODE REVIEW

**Comment by darrinmn9** [comment]
@sandstrom just wanted to clarify how you came to this, because maybe i am reading `caniuse` wrong. It seems that recent versions of edge, firefox, chrome, safari and safari on iOS all support INTL relative time. Am i incorrect? or has this been updated since ur PR?

https://caniuse.com/?search=relativetimeformat
Screen Shot 2021-06-09 at 4 30 32 PM

**Comment by sandstrom** [comment]
Yes, all the current ones support it. That's what I tried to express in the table too.

I also listed which versions doesn't support it. But in case that's too much info, we could also just list the minimum version for all browsers.

**Comment by darrinmn9** [comment]
gotcha, it just looks like a few of the `✗`'s in the `Intl relative time formatting` column could be changed to `✓`. (like mobile safari and edge)

**Comment by sandstrom** [comment]
@darrinmn9 You're right, thanks!

**Comment by sandstrom** [comment]
@icambron Let me know what you think!

**Comment by icambron** [comment]
I'll break support on Node 6 in the next minor, yeah. Which will be nice because it simplifies a lot of stuff for Luxon.

**Comment by icambron** [comment]
I ended up being much more aggressive and simply releasing 2.0 with huge changes to this matrix.

**Comment by sandstrom** [comment]
@icambron Awesome! 

Small suggestion here: https://github.com/moment/luxon/pull/969

**Pull request closed without merging**
