### PR TITLE
Adds weekday & month convenience getters

### PR DESCRIPTION
**Pull request by mslooten**
Adds the convenience getters as discussed in #48

### CODE REVIEW

**Comment by icambron** [comment]
This looks great. I'll figure out why the CI failed

**Comment by mslooten** [comment]
@icambron Thanks for checking. Yeah I was wondering about that too, only thing I'm unsure of is the circular import (datetime.js imports info.js which also imports datetime.js) to be able to use Info. But local tests & builds are fine.

**Comment by icambron** [comment]
Circular imports are OK with Rollup. If the library got bigger it would be a maintenance issue and I'd have to sort it out, but as it is I'm not too worried about it.

**Comment by icambron** [comment]
The CI problem was just Travis having some issues.

Can you add tests for a non-en-US locale? I usually use "fr". The reason for this is that Luxon has some fallback logic for older browsers that treats "en" and "en-US" specially.

**Comment by icambron** [comment]
Looks good, thanks! I'm going to push a new version in the next couple of days that includes this.

**Pull request merged**
