### PR TITLE
Midnight should return 12 for h, not 0

### PR DESCRIPTION
**Pull request by camflan**
`DateTime.fromISO('2017-12-01T00:00:00').toFormat('ha')` should output 12am, not 0am.

### CODE REVIEW

**Comment by icambron** [comment]
Oops, yup. Can you add tests for that too?

**Comment by camflan** [comment]
Sure thing

**Comment by icambron** [comment]
Looks good. I'll release this shortly

**Comment by icambron** [comment]
Released as 0.2.6. Thanks for the contribution!

**Pull request merged**
