### PR TITLE
Refactor test helpers

### PR DESCRIPTION
**Pull request by christianbender**
Issue #428 

* I removed the class in the file ```helpers.js``` (test directory). And changed the static methods into normal functions. 
* I changed various test files for importing this functions correctly

The tests run all correctly

### CODE REVIEW

**Comment by icambron** [comment]
@christianbender I can fix up the package-lock, but can you sign the CLA?

**Comment by christianbender** [comment]
@icambron  OK, thanks. How can I sign the CLA?

**Comment by christianbender** [comment]
@icambron Done. I sign the CLA now :smirk:

**Comment by icambron** [comment]
merged in 7b383aa1b75d494b158c0dd1096d40b253ceff53. Thanks for the contribution!

**Pull request closed without merging**
